export interface Schedule {
    hour?: number,
    minutes?: number,
    dais?: indexDay,
    username?: string,
    startTime?: string,
    startTime1?: string,
    startTime3?: string,
    changeStart?: any,
    endTime?: string,
    endTime1?: string,
    endTime3?: string,
    changeEnd?: any,
    startDate?: Date,
    endDate?: Date,
    startDate1?: Date,
    startDate3?: Date,
    endDate1?: Date,
    endDate3?: Date,
    diff?: number,
    changeUsername?: any,
    changeDais?: any,
    startTime2?: string,
    endTime2?: string,
    startTime4?: string,
    endTime4?: string,
    startTime5?: string,
    endTime5?: string,
    startTime6?: string,
    endTime6?: string,
    startDate2?: Date,
    startDate4?: Date,
    startDate5?: Date,
    startDate6?: Date,
    endDate4?: Date,
    endDate5?: Date,
    endDate6?: Date,
    endDate2?: Date,
    answer?: any
}

export enum indexDay {
    MO = "monday",
    TU = "tuesday",
    WE = "wednesday",
    TH = "thursday",
    FR = "friday",
    SA = "saturday",
    SU = "sunday"
}